# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f65ff82b553ac5de12b428182d09f02be6f455d3b9ca5142c02751bf34262063a4d9c997dc125b51fd4c8d88de450216e2dd8e3a3cf0af2a0efef521c884596f

test:
  secret_key_base: fc0eb8da23dfc650a9c52a433ef6d3d9b18db474b6f8f43b0c75da2ecd12333d15a9014a71d0c336c47fe5018ecb188a2bd3a701c94d0a634f7f1e55ae5dba46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
